### ISSUE TITLE
Diff bet PAS-network-environment-PrivateLink.json and PAS-network-environment-NAT.json

### ISSUE THREAD

**Issue by MayurvPawar** [cyberark/pas-on-cloud#125]
Hello Team, 

I am trying to understand what is the difference between PAS-network-environment-PrivateLink.json and PAS-network-environment-NAT.json CF Template. I dont see any documentation related to this ? If you guys can point me to right documentation that will be helpful. Also can you please help me in what scenarios do we need to use either templates?

Regards,
Mayur Pawar

**Comment by avishayil** [comment]
Hi @MayurvPawar ,
`PAS-network-environment-NAT.json` deploys NAT Gateway to the VPC's while `PAS-network-environment-PrivateLink.json` uses VPC Endpoints to communicate specifically with the required services. This is useful in cases customer policy does not allow Internet Gateway deployed in their VPC environment.
