### ISSUE TITLE
Make sure that the image has been properly prepared

### ISSUE THREAD

**Issue by akata72** [cyberark/pas-on-cloud#132]
I am getting the error below when trying to deploy the Vault Image.  It seems to be successfully downloaded and a image was created that I am using, but still getting the error below. Any thoughts? 

Deployment failed. Correlation ID: e2d255bc-c36b-4834-8dc3-5906d0010702. {
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "OSProvisioningClientError",
        "message": "OS provisioning for VM 'cavault' failed. Error details: This installation of Windows is undeployable. Make sure the image has been properly prepared (generalized).\r\nInstructions for Windows: https://azure.microsoft.com/documentation/articles/virtual-machines-windows-upload-image/ "
      }
    ]
  }
}

**Comment by zivshits** [comment]
Hi @akata72 ,
I have retested this again and I can see that Vault image is successfully deployed using our templates.
Can you please contact me thru mail so we can investigate this further?
ziv.lifshits@cyberark.com

Thanks in advance,
Ziv

**Comment by YouareGitHub** [comment]
I have an issue during the stack deployment with the vault image deliver, as below. out of interest when I search for  [ami-0cf1c48744ffdf9db] in EC2/AMI portal I can't see it under public or private. is this AMI available publicly? 


09 May 2019 08:30:41 | VaultMachine | CREATE_FAILED | API: ec2:RunInstances Not authorized for images: [ami-0cf1c48744ffdf9db]
-- | -- | -- | --

**Comment by zivshits** [comment]
AMIs are not publicly available. You should request AMI from Cyberark customer services.
Best regards,
Ziv

**Comment by zivshits** [comment]
No response so far from the reporter.
Closing the issue
