### ISSUE TITLE
VaultMachine CREATE_FAILED

### ISSUE THREAD

**Issue by YouareGitHub** [cyberark/pas-on-cloud#139]
I initially raised this under a separate issue thread but have now started a new issue for it.

I have an issue during the stack deployment (PAS-AIO-dr-Deployment.json) with the vault image delivery, as below. out of interest when I search for [ami-0cf1c48744ffdf9db] in EC2/AMI portal I can't see it under public or private AMI's in fact I can't see any of the AMI's for any of the regions. is this AMI available publicly?

09 May 2019 08:30:41 | VaultMachine | CREATE_FAILED | API: ec2:RunInstances Not authorized for images: [ami-0cf1c48744ffdf9db]
-- | -- | -- | --

**Comment by zivshits** [comment]
AMIs are provided by Cyberark customer services.

Best regards,
Ziv
