### ISSUE TITLE
Question: Availability Zones or Availability Sets

### ISSUE THREAD

**Issue by akata72** [cyberark/pas-on-cloud#144]
Hi guys, 
I see in your CyberArk documentation that a design using two different AvailabilityZones are recommended per component. I can't see that this is reflected in the ARM templates (only see that availability sets are used). Any comments on this?

Regards
Thomas, DNB

**Comment by avishayil** [comment]
@NoamALK @shiraberkovich

**Comment by DXM123** [comment]
It would be a real time saver if AZ’s are available during vm creation.
