### ISSUE TITLE
Question: PAS 10.10

### ISSUE THREAD

**Issue by akata72** [cyberark/pas-on-cloud#145]
Hi again, 

Just wanted to know when you expect to release ARM templates for version 10.10 (or if the existing templates can be used with the new version). 

Regards
Thomas, DNB

**Comment by akata72** [comment]
Any updates on this? I noticed that the Images for 10.10 can be downloaded. Can they be used with the ARM templates here?

**Comment by zivshits** [comment]
Azure was release today.
You can get latest AccessSAS from Cyberark Operations team.

Best regards,
Ziv
