### ISSUE TITLE
Question: PSM Scaling

### ISSUE THREAD

**Issue by akata72** [cyberark/pas-on-cloud#146]
Hi, 

Have you worked on any clever solution for scaling the PSM servers (in/out or up/down)?
We have an environment where concurrent PSM connections fluctuates between 0 and 500 during the week and would really like to minimize Azure compute cost.  

Regards
Thomas, DNB

**Comment by strick-j** [comment]
Hello Thomas,
You could take a look at this Ansible Role which allows auto deployment and registration of PSM servers via Ansible. 

https://github.com/cyberark/psm

Best,
Joe

**Comment by akata72** [comment]
Hi Joe,
Thanks for the tip. This could take us a bit forward, but we still need to find some way of deciding on the triggers for scaling up/down and how to implement that.  I.e when to start connection draining and adding/removing nodes from the loadbalancer and stuff like that. :-)

**Comment by zivshits** [comment]
Hello Thomas,
We are working on AWS auto-scaling first. The next will be Azure auto-scaling.

Best regards,
Ziv
