### ISSUE TITLE
copy recpub to bucket - Failed to create resource

### ISSUE THREAD

**Issue by uniqueperformtechsoft** [cyberark/pas-on-cloud#155]
Hi,

We are getting the following error message while create the single vault from the cloud formation template. But when I try in my local environment it is working fine. is there any document stating list for permissions needed to create the vault in AWS.

![AWS_vault Creation error](https://user-images.githubusercontent.com/23649717/64188528-3e755480-ce90-11e9-8d80-99e5c4c101c0.png)

**Comment by avishayil** [comment]
We are no longer using this logic, it is updated since #198
