### ISSUE TITLE
Missing PtaAccessSAS option in ./import-pas-images.ps1

### ISSUE THREAD

**Issue by DXM123** [cyberark/pas-on-cloud#261]
Hi,

Im missing the -PtaAccessSAS in the ./import-pas-images.ps1 script.
The documentation makes a references to this value.

https://docs.cyberark.com/Product-Doc/OnlineHelp/PAS/Latest/en/Content/PAS%20Cloud/Azure-Installation-Package.htm?tocpath=Installation%7CInstalling%20the%20PAS%C2%A0Solution%7CCloud%7CIntroduction%7C_____8#UsageExample

Is there an updated version available

**Comment by pelegor** [comment]
Hi, you are correct.
we added the parameter and it'll be part of the import-pas-images.ps1 script on the next release.
