### ISSUE TITLE
There is a problem with the default value of DR Vault VM Name.

### ISSUE THREAD

**Issue by usiusi360** [cyberark/pas-on-cloud#264]
Azure resource names cannot contain spaces.
   https://github.com/cyberark/pas-on-cloud/blob/f9d3e11/azure/pas-dr-deploy.json#L45

The default value for Primary follows the rules.
　https://github.com/cyberark/pas-on-cloud/blob/f9d3e11/azure/pas-vault-deploy.json#L88

**Comment by pelegor** [comment]
this fix will be included with the next release
