### ISSUE TITLE
Template is not running on AWS due to AMI Mismatch

### ISSUE THREAD

**Issue by kirtichoraria** [cyberark/pas-on-cloud#268]
## Summary
While running the Template on AWS using CloudFormation. Below error is seen:
API: ec2:RunInstances Not authorized for images: [ami-022d97240cd52f9f4

## Steps to Reproduce
1. Go to CloudFormation
2. Create New Stack 
3. Upload Template
4. Region should be ap-southeast-2
5. Fill all the relevant parameters
6. Run the template

## Expected Results
Instance should be created

## Actual Results (including error logs, if applicable)
Rollback initiated due to error in Vault Machine failed to create

## Reproducible
   * [ ] Always 
   
   
## Version/Tag number
What version of the product are you running? Any version info that you can share is helpful. 
For example, you might give the version from Docker logs, the Docker tag, a specific download URL, 
the output of the `/info` route, etc.

## Environment setup
Can you describe the environment in which this product is running? Is it running on a VM / in a container / in a cloud? 
Which cloud provider? Which container orchestrator (including version)? 
The more info you can share about your runtime environment, the better we may be able to reproduce the issue.

## Additional Information
![AMI Update required](https://user-images.githubusercontent.com/23231805/106528803-77aa6c00-653d-11eb-8fe5-395dc63313bf.JPG)

**Comment by dsmithuk** [comment]
It looks to me like they've solved this with yesterdays merge.
