### ISSUE TITLE
PSM unable to be deployed

### ISSUE THREAD

**Issue by bab29** [cyberark/pas-on-cloud#273]
https://github.com/cyberark/pas-on-cloud/blob/33e18969bea577956435f86afe86749477f5c1b2/aws/Full-PAS-Deployment.yaml#L1572

This appears to be the 12.0 not 12.1 version of the AMI.

**Comment by pelegor** [comment]
PSM was not included in 12.1 PAS on Cloud release.
You can find PSM v12.2 by now, sorry for the delayed response.
