### ISSUE TITLE
CyberArk Documentation describes a -ptaAccessSAS parameter which is not part  import-pas-images.ps1

### ISSUE THREAD

**Issue by Jayk423** [cyberark/pas-on-cloud#274]
The import-pas-images.ps1 script does not include support for importing the PTA images using the accessSAS links. However, the documentation describes this parameter -  https://docs.cyberark.com/Product-Doc/OnlineHelp/PAS/Latest/en/Content/PAS%20Cloud/Azure-Installation-Package.htm?Highlight=ptaaccesssas

**Comment by Jayk423** [comment]
Duplicate of #261

**Comment by pelegor** [comment]
>

**Comment by pelegor** [comment]
#261
