### ISSUE TITLE
Unable to deploy to West Central US, West US, East US 3 in Azure

### ISSUE THREAD

**Issue by bab29** [cyberark/pas-on-cloud#308]
After attempting to deploy to West US discovered we are where unable to deploy due to those regions not having availability zones. After research we discovered West Central US, West US, East US 3 do not currently have availability zones but this is not listed as a limitation anywhere.

**Comment by ggalfrin** [comment]
A fix to this issue was merged to branch “develop” (see PR https://github.com/cyberark/pas-on-cloud/pull/368) and will be part of the next version release.
