### ISSUE TITLE
The AMIs missing sysprep??

### ISSUE THREAD

**Issue by xueyang023** [cyberark/pas-on-cloud#34]
Hi guys,

Nothing to do with the CloudFormation templates which look great. But just wondering whether and how do you sysprep the CyberArk AMIs?
I'm manually testing ami-d18253b3 (Vaults) and ami-f896479a (Components) in ap-southeast-2 region, and found that all launched instances from them use the same machine names. I managed to sysprep ami-f896479a (Components) by myself, but fail to sysprep ami-d18253b3 (Vaults) with the following errors:

Info       [0x0f0080] SYSPRP ActionPlatform::LaunchModule: Found 'WSLicenseCleanUpState' in C:\Windows\System32\wsclient.dll; executing it
Info                  SYSPRP Entering WSLicenseCleanupState - Client Stub
Error                 SYSPRP WSLicenseCleanUpState failed with hr=c0020017
Info                  SYSPRP Exiting WSLicenseCleanupState - Client Stub
Error      [0x0f0082] SYSPRP ActionPlatform::LaunchModule: Failure occurred while executing 'WSLicenseCleanUpState' from C:\Windows\System32\wsclient.dll; dwRet = 0xc0020017
Error                 SYSPRP ActionPlatform::ExecuteAction: Error in executing action; dwRet = 0xc0020017
Error                 SYSPRP ActionPlatform::ExecuteActionList: Error in execute actions; dwRet = 0xc0020017
 Error                 SYSPRP SysprepSession::Execute: Error in executing actions from C:\Windows\System32\Sysprep\ActionFiles\Generalize.xml; dwRet = 0xc0020017
Error                 SYSPRP RunPlatformActions:Failed while executing SysprepSession actions; dwRet = 0xc0020017
Error      [0x0f0070] SYSPRP RunExternalDlls:An error occurred while running registry sysprep DLLs, halting sysprep execution. dwRet = 0xc0020017
Error      [0x0f00a8] SYSPRP WinMain:Hit failure while processing sysprep generalize internal providers; hr = 0xc0020017
Info       [0x0f004c] SYSPRP WaitThread:Exiting spawned waiting thread
Info       [0x0f0052] SYSPRP Shutting down SysPrep log

Any advice would be appreciated!
Thanks

**Comment by zivshits** [comment]
Hi @xueyang023 ,
We appreciate your feedback.
  In case of components we discovered that full sysprep cause huge spin-up time, hence we are only triggering password reset.
  With Vault AMIs we are performing full sysprep.
  Regarding hostnames we have developed optional host name field which enables hostname change when deploying single components.
  Same method can be applied to Vault AMI.

Does this makes sense for you?
Ziv

**Comment by xueyang023** [comment]
Hi @zivshits 
Thanks a lot for you reply and it helps. 
Could you please share a bit more details on:
1. How do you sysprep Vault AMI? Is there any special configs in "C:\Program Files\Amazon\Ec2ConfigService\Settings\Config.xml" ? Because it always failed for me when doing "C:\\Program Files\\Amazon\\Ec2ConfigService\\Ec2Config.exe\" -ArgumentList \"-sysprep\" -Wait"

2. Regarding the "optional hostname field" you mentioned, where exactly is it? is it part of CyberArk configuration wizard/command argument? or is it part of the CloudFormation script?

Thank you very much:)

**Comment by zivshits** [comment]
Hello @xueyang023 ,
We don't have anything special in Config.xml. During preparation of AMI we copy config.xml to its location and create AMI with the file, So next time sysprep will run.
Here is code snippet from our config.xml
`<GlobalSettings>
    <ManageShutdown>true</ManageShutdown>
    <SetDnsSuffixList>true</SetDnsSuffixList>
    <WaitForMetaDataAvailable>true</WaitForMetaDataAvailable>
    <ShouldAddRoutes>true</ShouldAddRoutes>
    <RemoveCredentialsfromSysprepOnStartup>true</RemoveCredentialsfromSysprepOnStartup>
  </GlobalSettings>`
I don't think running manually sysprep will work in case of Vault instance.

Regarding hostname field you can find it in *Single* templates for Vaul, DRVault and Components.

With best regards,
Ziv

**Comment by xueyang023** [comment]
Thank you very much Ziv!
