### ISSUE TITLE
Comments on the StorePasswordLamda function

### ISSUE THREAD

**Issue by aldomacias** [cyberark/pas-on-cloud#89]
Hi Guys, 

In the StorePasswordLambda function I think the first exception has a bad variable name, should be 'ssmclient' instead of 'client' and the ssmclient variable is not available to the lambda_handler function.  

I found this error when trying to automate a deployment with serverless using this Templates and send a invalid type of data for the Vault Admin Password.

Regards!

**Comment by avishayil** [comment]
Hey @aldomacias, Thank you for taking the time to review the template and making your comments.
We'll make sure to take this under consideration for the next update.
Regards,
Avishay Bar.

**Comment by zivshits** [comment]
Resolved
